version: '3.8'

services:
  
  modernuiapp:
    image: modernuiapp
    build:
      context: ./ModernUIAppSolution
      dockerfile: ModernUIApp.Dockerfile
    ports:
    - 9090:80
  
  modernapiapp:
    image: modernapiapp
    build:
      context: ./ModernApiAppSolution
      dockerfile: ModernApiApp.Dockerfile
    ports:
    - 8080:80
    depends_on:
      - modernapiapp.database
  
  modernapiapp.database:
    image: modernapiapp.database
    build:
      context: ./ModernApiAppSolution/ModernApiApp.Database
      dockerfile: ModernApiApp.Database.Dockerfile
    ports:
      - 5434:1433