# ModernApiApp:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main

pool:
 vmImage: 'windows-2019'

stages:
- stage: 'Build'
  displayName: 'Build and Test Customer API and Deploy to ACR'
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Execute Customer L0 Unit Test(s)'
      inputs:
       command: 'test'
       projects: '$(Build.SourcesDirectory)/ModernApiApp.Tests/ModernApiApp.Tests.csproj'
       testRunTitle: 'Execute Customer Unit Test'
       publishTestResults: true
       arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish Cobertura Code Coverage Results'
      inputs:
       codeCoverageTool: 'Cobertura'
       summaryFileLocation: '**/*coverage.cobertura.xml'
    - task: Docker@2
      displayName: 'Build Customer API and Deploy to ACR'
      inputs:
       containerRegistry: 'lodAcr'
       repository: 'modernapi'
       command: 'buildAndPush'
       Dockerfile: '$(Build.SourcesDirectory)/ModernApiApp.Dockerfile'
       tags: |
           $(Build.BuildNumber)
           Latest